2020-05-25 16:49:50,204 Exception on /images/uci_logo.png [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: images/uci_logo.png
2020-05-25 16:50:17,417 Exception on /images/uci_logo.jpg [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: images/uci_logo.jpg
2020-05-25 16:50:29,929 Exception on /images/uci_logo.jpg [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: images/uci_logo.jpg
2020-06-03 19:32:21,723 Exception on /templates/custom.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/custom.html
2020-06-03 19:37:00,229 Exception on /instructions/instruct-ready.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: instructions/instruct-ready.html
2020-06-03 19:38:15,272 Exception on /instructions/instruct-ready.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: instructions/instruct-ready.html
2020-06-03 19:42:16,258 Exception on /instructions/instruct-ready.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: instructions/instruct-ready.html
2020-06-03 19:43:47,338 Exception on /instructions/instruct-ready.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 749, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: instructions/instruct-ready.html
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17006)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17007)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17008)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17009)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17010)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17011)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17012)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17013)
[2020-06-03 21:09:32 -0700] [17003] [CRITICAL] WORKER TIMEOUT (pid:17014)
[2020-06-03 21:09:40 -0700] [17392] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17387] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17386] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17388] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17390] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17393] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17385] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:41 -0700] [17389] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-03 21:09:40 -0700] [17391] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.my_custom_view
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17264)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17265)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17266)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17267)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17268)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17269)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17270)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17271)
[2020-06-13 16:57:42 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17272)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17646)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17647)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17650)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17651)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17652)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17653)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17654)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17655)
[2020-06-13 17:56:09 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17656)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17995)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17996)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17997)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17998)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:17999)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18000)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18001)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18002)
[2020-06-13 18:56:19 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18003)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18008)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18009)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18010)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18011)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18012)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18015)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18016)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18017)
[2020-06-13 19:01:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18018)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18023)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18024)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18025)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18026)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18027)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18028)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18031)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18032)
[2020-06-13 19:06:14 -0700] [17261] [CRITICAL] WORKER TIMEOUT (pid:18033)
[2020-06-18 20:06:48 -0700] [3429] [CRITICAL] WORKER TIMEOUT (pid:3433)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16933)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16934)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16935)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16936)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16937)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16938)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16939)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16940)
[2020-06-22 23:25:10 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:16941)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17663)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17664)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17665)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17666)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17667)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17668)
[2020-06-22 23:26:00 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17669)
[2020-06-22 23:26:01 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17670)
[2020-06-22 23:26:01 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17671)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17681)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17682)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17683)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17684)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17685)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17686)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17687)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17688)
[2020-06-23 01:26:03 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17689)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17691)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17692)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17694)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17696)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17698)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17700)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17701)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17702)
[2020-06-23 03:26:13 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17703)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17707)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17708)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17709)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17710)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17711)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17712)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17713)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17714)
[2020-06-23 05:26:23 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17715)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17723)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17724)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17725)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17726)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17727)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17728)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17729)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17730)
[2020-06-23 07:26:04 -0700] [16930] [CRITICAL] WORKER TIMEOUT (pid:17731)
2020-06-28 15:30:02,390 Entered /save_data_file
2020-06-28 15:51:51,284 Entered /save_data_file
2020-06-28 15:56:44,881 Entered /save_data_file
2020-06-28 16:01:56,291 Entered /save_data_file
2020-06-28 16:50:08,644 Entered /save_data_file
2020-06-28 16:52:11,541 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 16:52:25,945 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 16:53:37,956 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
[2020-06-28 16:54:08 -0700] [5624] [CRITICAL] WORKER TIMEOUT (pid:5632)
2020-06-28 16:55:44,219 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 16:55:51,912 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:00:34,744 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:02:27,624 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:03:07,906 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:04:48,108 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:05:13,320 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:07:19,901 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:10:00,911 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:10:20,374 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:10:39,282 Exception on /olifequestionnaire.html [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: olifequestionnaire.html
2020-06-28 17:34:32,926 Entered /save_data_file
[2020-07-07 19:06:32 -0700] [25471] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25470] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25472] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25473] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25474] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25475] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25478] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25476] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:06:33 -0700] [25477] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:45 -0700] [25507] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:45 -0700] [25508] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25509] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25510] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25511] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25512] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25513] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25514] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:07:46 -0700] [25515] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25599] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25601] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25600] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25602] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25604] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25603] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25606] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25605] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-07 19:09:19 -0700] [25607] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
2020-07-07 19:21:35,534 Entered /save_data_file
2020-07-07 19:31:53,321 Entered /save_data_file
2020-07-07 19:32:01,943 Exception on /save_data_file [GET]
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 747, in regularpage
    return render_template(pagename)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: save_data_file
2020-07-07 19:35:30,781 Entered /save_data_file
2020-07-07 19:40:58,956 Entered /save_data_file
2020-07-07 19:43:21,985 Entered /save_data_file
[2020-07-12 14:25:34 -0700] [77012] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:34 -0700] [77013] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77014] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77017] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77016] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77015] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77018] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77019] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
[2020-07-12 14:25:35 -0700] [77020] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/psiturk/experiment.py", line 87, in <module>
    app.register_blueprint(custom_code)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 224, in register
    deferred(state)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 245, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/michelleliang/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: custom_code.save_data_file
2020-07-12 14:29:34,134 Entered /save_data_file
2020-07-12 14:36:02,215 Entered /save_data_file
2020-07-12 14:54:03,411 Entered /save_data_file
2020-07-14 07:27:13,676 Entered /save_data_file
2020-07-14 07:40:32,438 Entered /save_data_file
2020-07-14 07:46:55,838 Entered /save_data_file
2020-07-14 07:51:42,223 Entered /save_data_file
[2020-07-14 10:30:04 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5364)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5363)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5365)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5366)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5367)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5368)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5369)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5370)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5371)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5372)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5373)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5374)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5375)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5376)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5377)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5378)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5379)
[2020-07-14 11:11:20 -0700] [5017] [CRITICAL] WORKER TIMEOUT (pid:5420)
